pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
    steps {
        sh 'docker build -t taskmanager ./devops-taskmanager'
    }
}

        stage('Stop Old Container') {
            steps {
                sh 'docker rm -f taskmanager || true'
            }
        }

        stage('Run Container') {
            steps {
                sh 'docker run -d --name taskmanager -p 5000:5000 taskmanager'
            }
        }
    }
}